# Configuration file for Prettier
# Used before every commit to format the code-style

printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
arrowParens: avoid
