language: node_js
node_js:
  - 'lts/*'
install:
  - npm ci
script:
  - npm run prettier:check
  - npm run lint:check
  - npm run test:ci
before_deploy:
  - npm run build
  - cp LICENSE build/LICENSE
  - cp README.md build/README.md
  - cp package.json build/package.json
  - cp package-lock.json build/package-lock.json
  - cd build
deploy:
  provider: npm
  email: npm-ci-write@spreadmonitor.com
  api_key:
    secure: $NPM_PUBLISH_TOKEN
  on:
    branch: master
  skip_cleanup: true
